steps:
- name: golang
  args: ['go', 'build', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE', '.' ]
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE'